networks:

  traefik:
    external: true

  dolibarr:
    enable_ipv6: true

services:

  dolibarr:

    container_name: dolibarr
    hostname: dolibarr

    # https://hub.docker.com/r/tuxgasy/dolibarr/tags
    image: tuxgasy/dolibarr:17.0.2

    depends_on:
      dolibarr-db:
        condition: service_healthy
        restart: true

    networks:
      - traefik
      - dolibarr

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.dolibarr.rule=Host(`dolibarr.stb.de`)
      - traefik.http.services.dolibarr.loadbalancer.server.port=80

      # homepage
      - homepage.group=dolibarr (.stb.de)
      - homepage.name=dolibarr (dolibarr.stb.de)
      - homepage.weight=-999
      - homepage.description=tuxgasy/dolibarr
      - homepage.showStats=true
      - homepage.icon=dolibarr.png
      - homepage.href=https://dolibarr.stb.de
      - homepage.ping=https://dolibarr.stb.de

    env_file:
      - ./configuration/dolibarr.env

    volumes:
      - /etc/localtime:/etc/localtime:ro

    restart: unless-stopped

    healthcheck:
      test: curl -s --fail http://localhost

  dolibarr-db:

    container_name: dolibarr-db
    hostname: dolibarr-db

    # https://hub.docker.com/_/mariadb/tags
    image: mariadb:11.0.3-jammy

    networks:
      - dolibarr

    labels:

      # homepage
      - homepage.group=dolibarr (.stb.de)
      - homepage.name=dolibarr-db
      - homepage.description=mariadb
      - homepage.showStats=true
      - homepage.icon=mariadb.png

    restart: unless-stopped

    env_file:
      - ./configuration/db.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db:/var/lib/mysql:cached

    healthcheck:
      test: healthcheck.sh --su=root --connect --innodb_initialized
      start_period: 15s
