networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # https://hub.docker.com/_/yourls
  yourls:

    # image, build, depends_on, command
    image: yourls:1.9.2-apache
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.yourls.rule=Host(`yourls.stb.de`)
      - traefik.http.routers.yourls.tls.domains[0].main=yourls.stb.de
      - traefik.http.routers.yourls.tls.domains[0].sans=*.yourls.stb.de
      - traefik.http.services.yourls.loadbalancer.server.port=80

      # homepage
      - homepage.weight=-999
      - homepage.group=yourls (.stb.de)
      - homepage.name=yourls
      - homepage.description=yourls:1.9.2-apache
      - homepage.icon=yourls.png
      - homepage.href=https://yourls.stb.de/admin
      - homepage.ping=https://yourls.stb.de/css/cal.css
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default
      - traefik

    # env_file, environment
    env_file:
      - ./config/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

    # healthcheck, restart
    healthcheck:
      test: curl -s --fail http://localhost/admin
    restart: unless-stopped

  # https://hub.docker.com/_/mariadb
  mariadb:

    # image, build, depends_on, command
    image: mariadb:11.0.3-jammy

    # labels
    labels:

      # homepage
      - homepage.group=yourls (.stb.de)
      - homepage.name=mariadb
      - homepage.description=mariadb:11.0.3-jammy
      - homepage.icon=mariadb.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # env_file, environment
    env_file:
      - ./config/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/mariadb/mysql:/var/lib/mysql:cached

    # healthcheck, restart
    healthcheck:
      test: healthcheck.sh --su=root --connect --innodb_initialized
      start_period: 15s
    restart: unless-stopped
