networks:

  traefik:
    external: true


services:

  main:
  # add users: docker run --rm --entrypoint htpasswd httpd:2 -Bbn username password >> ./volumes/auth/.htpasswd

    # https://hub.docker.com/_/registry/tags
    image: registry:2.8.2

    networks:
      - traefik

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.registry.rule=Host(`registry.stb.de`)
      - traefik.http.services.registry.loadbalancer.server.port=5000

      - traefik.http.routers.registry.tls.certresolver=stbde
      - traefik.http.routers.registry.tls.domains[0].main=registry.stb.de
      - traefik.http.routers.registry.tls.domains[0].sans=*.registry.stb.de


      # homepage
      - homepage.group=docker
      - homepage.name=registry(.stb.de)
      - homepage.description=registry
      - homepage.showStats=true
      - homepage.icon=docker.png
      - homepage.href=https://registry.stb.de/v2
      - homepage.ping=https://registry.stb.de

    restart: unless-stopped

    env_file:
      - ./env/registry.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/auth:/auth:cached
      - ./volumes/data:/var/lib/registry:cached

    healthcheck:
      test: wget -q --spider http://127.0.0.1:5000
      timeout: 5s
      interval: 15s
      start_period: 10s
      retries: 3
