networks:

  traefik:
    external: true

services:

  # https://hub.docker.com/_/registry
  # add users: docker run --rm --entrypoint htpasswd httpd:2 -Bbn username password >> ./config/auth/.htpasswd
  registry:

    # image, build, depends_on, command
    image: registry:2.8.2

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.registry.rule=Host(`registry.stb.de`)
      - traefik.http.services.registry.loadbalancer.server.port=5000

      # homepage
      - homepage.group=registry (.stb.de)
      - homepage.name=registry
      - homepage.description=registry:2.8.2
      - homepage.icon=docker.png
      - homepage.href=https://registry.stb.de/v2
      - homepage.ping=https://registry.stb.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - traefik

    # env_file, environment
    env_file:
      - ./config/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # config
      - ./config/auth:/auth:cached

      # data
      - ./data/data:/var/lib/registry:cached

    # healthcheck, restart
    healthcheck:
      test: wget -q --spider http://127.0.0.1:5000
    restart: unless-stopped
