networks:

  traefik:
    external: true

services:

  # https://github.com/benphelps/homepage/pkgs/container/homepage
  homepage:

    # image, build, depends_on, command
    image: ghcr.io/benphelps/homepage:v0.6.33

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.dockerstats.rule=Host(`dockerstats.stb.de`)
      - traefik.http.services.dockerstats.loadbalancer.server.port=3000

      # homepage
      - homepage.group=dockerstats (.stb.de)
      - homepage.name=homepage
      - homepage.description=ghcr.io/benphelps/homepage:v0.6.33
      - homepage.icon=homepage.png
      - homepage.href=https://dockerstats.stb.de
      - homepage.ping=https://dockerstats.stb.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - traefik

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # socket
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # config
      - ./config/config:/app/config:ro
      - ./config/images:/app/public/images:ro

      # data
      - ./data/logs:/logs

    # healthcheck, restart
    restart: unless-stopped
