networks:

  traefik:
    external: true

services:

  # https://hub.docker.com/_/traefik
  traefik:

    # image, build, depends_on, command
    image: traefik:v3.0

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.stb.de`)
      - traefik.http.routers.traefik.tls.certresolver=hetznerdns
      - traefik.http.routers.traefik.tls.domains[0].main=traefik.stb.de
      - traefik.http.routers.traefik.tls.domains[0].sans=*.traefik.stb.de
      - traefik.http.services.traefik.loadbalancer.server.port=8080

      # homepage
      - homepage.group=traefik (.stb.de)
      - homepage.name=traefik
      - homepage.description=traefik:v3.0
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.stb.de/dashboard
      - homepage.ping=https://traefik.stb.de/dashboard
      - homepage.showStats=true

      # homepage.widget
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik.stb.de

    # container_name, hostname, networks, ports
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080

    # env_file, environment
    env_file:
      - ./config/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # socket
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # config
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro

      # data
      - ./data/letsencrypt:/letsencrypt:cached

    # healthcheck, restart
    healthcheck:
      # Run traefik healthcheck command
      # https://doc.traefik.io/traefik/operations/cli/#healthcheck
      # ! depends on: ping=true
      test: traefik healthcheck --ping
    restart: unless-stopped
