networks:

  traefik:
    external: true

services:

  traefik:
  # https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/

    container_name: traefik
    hostname: traefik

    # https://hub.docker.com/_/traefik/tags
    image: traefik:v2.10.4

    ports:
      - 80:80
      - 443:443
      - 8080:8080

    networks:
      - traefik

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.stb.de`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080

      - traefik.http.routers.traefik.tls.certresolver=stbde
      - traefik.http.routers.traefik.tls.domains[0].main=traefik.stb.de
      - traefik.http.routers.traefik.tls.domains[0].sans=*.traefik.stb.de

      - traefik.tls.stores.default.defaultgeneratedcert.resolver=stbde
      - traefik.tls.stores.default.defaultgeneratedcert.domain.main=stb.de
      - traefik.tls.stores.default.defaultgeneratedcert.domain.sans=*.stb


      # homepage
      - homepage.group=docker
      - homepage.name=traefik (.stb.de)
      - homepage.weight=-999
      - homepage.description=traefik
      - homepage.showStats=true
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.stb.de/dashboard
      - homepage.ping=https://traefik.stb.de/dashboard

      # homepage.widget
      - homepage.widget.type=traefik
      - homepage.widget.url=http://traefik.stb.de

    restart: unless-stopped

    env_file:
      - ./env/traefik.env

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./volumes/letsencrypt:/letsencrypt:cached

    healthcheck:
    # Run traefik healthcheck command
    # https://doc.traefik.io/traefik/operations/cli/#healthcheck
    # ! depends on: ping=true
      test: traefik healthcheck --ping
      timeout: 5s
      interval: 15s
      start_period: 10s
      retries: 3
