networks:

  traefik:
    external: true

services:

  traefik:
    # https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/

    container_name: traefik
    hostname: traefik

    # https://hub.docker.com/_/traefik/tags
    image: traefik:v3.0

    ports:
      - 80:80
      - 443:443
      - 8080:8080

    networks:
      - traefik

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.stb.de`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080

      # homepage
      - homepage.group=docker
      - homepage.name=traefik (.stb.de)
      - homepage.weight=-999
      - homepage.description=traefik
      - homepage.showStats=true
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.stb.de/dashboard
      - homepage.ping=https://traefik.stb.de/dashboard

      # homepage.widget
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik.stb.de

    restart: unless-stopped

    env_file:
      - ./configuration/traefik.env

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./configuration/traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml:ro
      - ./volumes/letsencrypt:/letsencrypt:cached

    healthcheck:
      # Run traefik healthcheck command
      # https://doc.traefik.io/traefik/operations/cli/#healthcheck
      # ! depends on: ping=true
      test: traefik healthcheck --ping
