version: "3.8"

networks:

  traefik:
    external: true

services:

  main:
  # https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/

    #image: traefik
    image: registry.stb.de/traefik

    ports:
      - 80:80
      - 443:443
      - 8080:8080

    networks:
      - traefik

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.stb.de`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080

      - traefik.http.routers.traefik.tls.certresolver=stbde
      - traefik.http.routers.traefik.tls.domains[0].main=traefik.stb.de
      - traefik.http.routers.traefik.tls.domains[0].sans=*.traefik.stb.de


      # homepage
      - homepage.group=docker
      - homepage.name=traefik(.stb.de)
      - homepage.weight=-999
      - homepage.description=traefik
      - homepage.showStats=true
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.stb.de/dashboard
      - homepage.ping=https://traefik.stb.de/dashboard

      # homepage.widget
      - homepage.widget.type=traefik
      - homepage.widget.url=http://traefik.stb.de

    restart: unless-stopped

    #mem_reservation: 32m
    #mem_limit: 64m

    command: 

      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik

      - --api.insecure=true 
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443

      # force redirect: http -> https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=webmaster@stb-host.de
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

      - --certificatesresolvers.stbde.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.stbde.acme.dnschallenge.provider=hetzner
      - --certificatesresolvers.stbde.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.stbde.acme.email=webmaster@stb-host.de
      - --certificatesresolvers.stbde.acme.storage=/letsencrypt/stb_de_hetzner_acme.json

      # allow ping
      - --ping=true
     
    env_file:
      - ./env/traefik.env

    volumes:
      - ./volumes/letsencrypt:/letsencrypt:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

    healthcheck:
    # Run traefik healthcheck command
    # https://doc.traefik.io/traefik/operations/cli/#healthcheck
    # ! depends on: ping=true
      test: traefik healthcheck --ping
      timeout: 5s
      interval: 15s
      start_period: 10s
      retries: 3