services:

  main:

    image: watchtower-alpine:1.5.3-3.18.3

    build:
      context: build

      args:

        # https://hub.docker.com/r/containrrr/watchtower/tags
        baseImage: containrrr/watchtower:1.5.3

        # https://hub.docker.com/_/alpine/tags
        alpineImage: alpine:3.18.3

      tags:
        - watchtower-alpine:1.5.3-3.18.3

    labels:

      # homepage
      - homepage.group=docker
      - homepage.name=watchtower
      - homepage.description=containrrr/watchtower
      - homepage.showStats=true
      - homepage.icon=watchtower.png

    restart: unless-stopped

    env_file:
      - ./env/watchtower.env

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
