networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # https://hub.docker.com/r/kimai/kimai2
  kimai:

    # image, build, depends_on, command
    image: kimai/kimai2:apache-2.0.26-prod
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.kimai.rule=Host(`kimai.stb.de`)
      - traefik.http.routers.kimai.tls.domains[0].main=kimai.stb.de
      - traefik.http.routers.kimai.tls.domains[0].sans=*.kimai.stb.de
      - traefik.http.services.kimai.loadbalancer.server.port=8001

      # homepage
      - homepage.weight=-999
      - homepage.group=kimai (.stb.de)
      - homepage.name=kimai
      - homepage.description=kimai/kimai2:apache-2.0.26-prod
      - homepage.icon=kimai.png
      - homepage.href=https://kimai.stb.de
      - homepage.ping=https://kimai.stb.de/de/login
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default
      - traefik

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/kimai/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

    # healthcheck, restart
    restart: unless-stopped

  # https://hub.docker.com/_/mariadb
  mariadb:

    # image, build, depends_on, command
    image: mariadb:11.0.3-jammy

    # labels
    labels:

      # homepage
      - homepage.weight=-100
      - homepage.group=kimai (.stb.de)
      - homepage.name=mariadb
      - homepage.description=mariadb:11.0.3-jammy
      - homepage.icon=mariadb.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/mariadb/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/mariadb/mysql:/var/lib/mysql:cached

    # healthcheck, restart
    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s
    restart: unless-stopped
