api:
  insecure: true
  
providers:

  file:
    filename: /etc/traefik/traefik.dynamic.yml

  docker: 
    exposedByDefault: false
    network: traefik

entryPoints:
  
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

ping: {}

certificatesResolvers:

  stbde:
    acme:
      email: "webmaster@stb-host.de"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: hetzner