networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  web:

    # https://hub.docker.com/_/nginx/tags?name=alpine
    image: nginx:1.25-alpine3.18

    depends_on:

      app:
        condition: service_healthy
        restart: true

    networks:
      - default
      - traefik

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.sportsyouthconnected.rule=Host(`sportsyouthconnected.de`)
      - traefik.http.services.sportsyouthconnected.loadbalancer.server.port=80

      # homepage
      - homepage.group=sportsyouthconnected (.de)
      - homepage.name=web
      - homepage.weight=-999
      - homepage.description=nginx:alpine
      - homepage.showStats=true
      - homepage.icon=nginx.png
      - homepage.href=https://sportsyouthconnected.de
      - homepage.ping=https://sportsyouthconnected.de

    volumes:
      - ./configuration/nginx:/etc/nginx/conf.d:ro
      - ./volumes/wordpress:/var/www/html:cached

    restart: unless-stopped

    healthcheck:
      test: curl -s --fail http://localhost


  app:

    # https://hub.docker.com/_/wordpress/tags
    image: wordpress:6.3.0-php8.2-fpm-alpine
    restart: unless-stopped

    depends_on:

      db:
        condition: service_healthy
        restart: true

    networks:
      - default

    labels:

      # homepage
      - homepage.group=sportsyouthconnected (.de)
      - homepage.name=app
      - homepage.weight=-100
      - homepage.description=wordpress:fpm-alpine
      - homepage.showStats=true
      - homepage.icon=wordpress.png

    env_file:
      - ./configuration/wordpress.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini:ro
      - ./volumes/wordpress:/var/www/html:cached

    healthcheck:
      test: netstat -tnlp | grep fpm -q


  db:

    # https://hub.docker.com/_/mariadb/tags
    image: mariadb:11.0.3-jammy
    restart: unless-stopped

    networks:
      - default

    env_file:
      - ./configuration/db.env

    volumes:
      - ./volumes/db:/var/lib/mysql:cached
      - /etc/localtime:/etc/localtime:ro

    labels:

      # homepage
      - homepage.group=sportsyouthconnected (.de)
      - homepage.name=db
      - homepage.weight=0
      - homepage.description=mariadb
      - homepage.showStats=true
      - homepage.icon=mariadb.png

    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s
