networks:

  traefik:
    external: true

services:

  # https://hub.docker.com/r/portainer/portainer-ce
  portainer:

    # image, build, depends_on, command
    image: portainer/portainer-ce:2.18.4-alpine

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.stb.de`)
      - traefik.http.routers.portainer.tls.domains[0].main=portainer.stb.de
      - traefik.http.routers.portainer.tls.domains[0].sans=*.portainer.stb.de
      - traefik.http.services.portainer.loadbalancer.server.port=9000

      # homepage
      - homepage.group=portainer (.stb.de)
      - homepage.name=portainer
      - homepage.description=portainer/portainer-ce:2.18.4-alpine
      - homepage.icon=portainer.png
      - homepage.href=https://portainer.stb.de
      - homepage.ping=https://portainer.stb.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - traefik

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # socket
      - /var/run/docker.sock:/var/run/docker.sock

      # data
      - ./data/data:/data:cached

    # healthcheck, restart
    healthcheck:
      test: wget -q --spider http://127.0.0.1:9000
    restart: unless-stopped
