networks:

  default:
    enable_ipv6: true

  traefik:
    external: true


services:

  web:

    # https://hub.docker.com/r/freshrss/freshrss/
    image: freshrss/freshrss:1.21.0-alpine
    restart: unless-stopped

    depends_on:

      db:
        condition: service_healthy
        restart: true

    networks:
      - default
      - traefik

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`freshrss.stb.de`)
      - traefik.http.services.freshrss.loadbalancer.server.port=80

      # homepage
      - homepage.weight=-100
      - homepage.group=freshrss (.stb.de)
      - homepage.name=web
      - homepage.description=freshrss/freshrss:1.21.0-alpine
      - homepage.showStats=true
      - homepage.icon=freshrss.png
      - homepage.href=https://freshrss.stb.de
      - homepage.ping=https://freshrss.stb.de

    env_file:
      - ./config/freshrss.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/data:/var/www/FreshRSS/data:cached
      - ./volumes/extensions:/var/www/FreshRSS/extensions:cached

    #healthcheck:
    #  test: wget --spider localhost

  db:

    # https://hub.docker.com/_/mariadb/tags
    image: mariadb:11.0.3-jammy
    restart: unless-stopped

    networks:
      - default

    env_file:
      - ./config/db.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db:/var/lib/mysql:cached

    labels:

      # homepage
      - homepage.group=freshrss (.stb.de)
      - homepage.name=db
      - homepage.description=mariadb
      - homepage.showStats=true
      - homepage.icon=mariadb.png

    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s
