networks:

  traefik:
    external: true

  matomo:
    enable_ipv6: true


services:

  web:

    image: nginx:1.25-alpine3.18

    networks:
      - matomo
      - traefik

    restart: unless-stopped

    depends_on:

      app:
        condition: service_healthy
        restart: true

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/matomo:/var/www/html:cached
      # see https://github.com/matomo-org/matomo-nginx
      - ./config/matomo.conf:/etc/nginx/conf.d/default.conf:ro

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.matomo.rule=Host(`matomo.stb.de`)
      - traefik.http.services.matomo.loadbalancer.server.port=80

      # homepage
      - homepage.weight=-200
      - homepage.group=matomo (.stb.de)
      - homepage.name=web
      - homepage.description=nginx
      - homepage.showStats=true
      - homepage.icon=nginx.png
      - homepage.href=https://matomo.stb.de
      - homepage.ping=https://matomo.stb.de

  app:

    image: matomo:fpm-alpine

    networks:
      - matomo

    restart: unless-stopped

    depends_on:

      db:
        condition: service_healthy
        restart: true

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/matomo:/var/www/html:cached
      - ./volumes/config:/var/www/html/config:cached
      - ./volumes/logs:/var/www/html/logs:cached

    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=8192M

    env_file:
      - ./config/db.env

    healthcheck:
      test: netstat -tnlp | grep fpm -q

    labels:

      # homepage
      - homepage.weight=-100
      - homepage.group=matomo (.stb.de)
      - homepage.name=app
      - homepage.description=matomo
      - homepage.showStats=true
      - homepage.icon=matomo.png

  db:

    image: mariadb:11.0.3-jammy

    networks:
      - matomo

    command: --max-allowed-packet=64MB

    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db:/var/lib/mysql
      #- ./matomo.sql:/docker-entrypoint-initdb.d/dump.sql

    env_file:
      - ./config/db.env

    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s

    labels:

      # homepage
      - homepage.weight=0
      - homepage.group=matomo (.stb.de)
      - homepage.name=db
      - homepage.description=mariadb
      - homepage.showStats=true
      - homepage.icon=mariadb.png