networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # https://hub.docker.com/_/nginx
  nginx:

    # image, build, depends_on, command
    image: nginx:1.25-alpine3.18
    depends_on:
      matomo:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.matomo.rule=Host(`matomo.stb.de`)
      - traefik.http.routers.matomo.tls.domains[0].main=matomo.stb.de
      - traefik.http.routers.matomo.tls.domains[0].sans=*.matomo.stb.de
      - traefik.http.services.matomo.loadbalancer.server.port=80

      # homepage
      - homepage.weight=-999
      - homepage.group=matomo (.stb.de)
      - homepage.name=nginx
      - homepage.description=nginx:1.25-alpine3.18
      - homepage.icon=nginx.png
      - homepage.href=https://matomo.stb.de
      - homepage.ping=https://matomo.stb.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default
      - traefik

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # config
      # see https://github.com/matomo-org/matomo-nginx
      - ./config/nginx/matomo.conf:/etc/nginx/conf.d/default.conf:ro

      # data
      - ./data/matomo/html:/var/www/html:cached

    # healthcheck, restart
    restart: unless-stopped

  matomo:

    # image, build, depends_on, command
    image: matomo:4.15.1-fpm-alpine
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # homepage
      - homepage.weight=-101
      - homepage.group=matomo (.stb.de)
      - homepage.name=matomo
      - homepage.description=matomo:4.15.1-fpm-alpine
      - homepage.icon=matomo.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/matomo/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/matomo/html:/var/www/html:cached
      - ./data/matomo/config:/var/www/html/config:cached
      - ./data/matomo/logs:/var/www/html/logs:cached

    # healthcheck, restart
    healthcheck:
      test: netstat -tnlp | grep fpm -q
    restart: unless-stopped

  # https://hub.docker.com/_/mariadb
  mariadb:

    # image, build, depends_on, command
    image: mariadb:11.0.3-jammy
    command: --max-allowed-packet=64MB

    #labels
    labels:

      # homepage
      - homepage.weight=-100
      - homepage.group=matomo (.stb.de)
      - homepage.name=mariadb
      - homepage.description=mariadb:11.0.3-jammy
      - homepage.icon=mariadb.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/mariadb/.env

    #volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/mariadb/mysql:/var/lib/mysql:cached

    # healthcheck, restart
    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s
    restart: unless-stopped
