networks:

  default:
    enable_ipv6: true

  traefik:
    external: true

services:

  # https://hub.docker.com/r/paperlessngx/paperless-ngx
  paperlessngx:

    # image, build, depends_on, command
    image: paperlessngx/paperless-ngx:1.17.1
    depends_on:

      redis:
        condition: service_healthy
        restart: true

      mariadb:
        condition: service_healthy
        restart: true

    # labels
    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.paperlessngx.rule=Host(`paperlessngx.stb.de`)
      - traefik.http.services.paperlessngx.loadbalancer.server.port=8000

      # homepage
      - homepage.weight=-999
      - homepage.group=paperlessngx (.stb.de)
      - homepage.name=paperlessngx
      - homepage.description=paperlessngx/paperless-ngx:1.17.1
      - homepage.icon=paperless.png
      - homepage.href=https://paperlessngx.stb.de
      - homepage.ping=https://paperlessngx.stb.de
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default
      - traefik

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/paperlessngx/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/paperlessngx/consume:/usr/src/paperless/consume
      - ./data/paperlessngx/data:/usr/src/paperless/data
      - ./data/paperlessngx/export:/usr/src/paperless/export
      - ./data/paperlessngx/media:/usr/src/paperless/media

    # healthcheck, restart
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
    restart: unless-stopped

  # https://hub.docker.com/_/redis
  redis:

    # image, build, depends_on, command
    image: redis:7.2.0-alpine3.18

    # labels
    labels:

      # homepage
      - homepage.weight=-500
      - homepage.group=paperlessngx (.stb.de)
      - homepage.name=redis
      - homepage.description=redis:7.2.0-alpine3.18
      - homepage.icon=redis.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

    # healthcheck, restart
    healthcheck:
      test: redis-cli ping | grep PONG -q
    restart: unless-stopped

  # https://hub.docker.com/_/mariadb
  mariadb:

    # image, build, depends_on, command
    #! PaperlessNGX: 10.11.5-jammy
    image: mariadb:10.11.5-jammy

    # labels
    labels:

      # homepage
      - homepage.weight=-100
      - homepage.group=paperlessngx (.stb.de)
      - homepage.name=mariadb
      - homepage.description=mariadb:10.11.5-jammy
      - homepage.icon=mariadb.png
      - homepage.showStats=true

    # container_name, hostname, networks, ports
    networks:
      - default

    # env_file, environment
    env_file:
      - ./config/.env
      - ./config/mariadb/.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ./data/mariadb/mysql:/var/lib/mysql:cached

    # healthcheck, restart
    healthcheck:
      test: healthcheck.sh --su=root --connect --innodb_initialized
      start_period: 15s
    restart: unless-stopped
