networks:

  traefik:
    external: true

  paperlessngx:
    enable_ipv6: true

services:

  paperlessngx:

    container_name: paperlessngx
    hostname: paperlessngx

    # https://hub.docker.com/r/paperlessngx/paperless-ngx/tags
    image: paperlessngx/paperless-ngx:1.17.1

    depends_on:

      paperlessngx-redis:
        condition: service_healthy
        restart: true

      paperlessngx-db:
        condition: service_healthy
        restart: true

    networks:
      - traefik
      - paperlessngx

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.paperlessngx.rule=Host(`paperlessngx.stb.de`)
      - traefik.http.services.paperlessngx.loadbalancer.server.port=8000

      # homepage
      - homepage.group=paperlessngx (.stb.de)
      - homepage.name=paperlessngx (paperlessngx.stb.de)
      - homepage.weight=-999
      - homepage.description=paperlessngx/paperless-ngx
      - homepage.showStats=true
      - homepage.icon=paperless.png
      - homepage.href=https://paperlessngx.stb.de
      - homepage.ping=https://paperlessngx.stb.de

    restart: unless-stopped

    env_file: ./configuration/paperlessngx.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/paperless/consume:/usr/src/paperless/consume
      - ./volumes/paperless/data:/usr/src/paperless/data
      - ./volumes/paperless/export:/usr/src/paperless/export
      - ./volumes/paperless/media:/usr/src/paperless/media

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]

  paperlessngx-redis:

    container_name: paperlessngx-redis
    hostname: paperlessngx-redis

    image: redis:7.2.0-alpine3.18

    networks:
      - paperlessngx

    labels:

      # homepage
      - homepage.group=paperlessngx (.stb.de)
      - homepage.name=paperlessngx-redis
      - homepage.description=redis:7-alpine
      - homepage.showStats=true
      - homepage.icon=redis.png

    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro

    healthcheck:
      test: redis-cli ping | grep PONG -q

  paperlessngx-db:

    container_name: paperlessngx-db
    hostname: paperlessngx-db

    # PaperlessNGX: 10.11.5-jammy
    # https://hub.docker.com/_/mariadb/tags
    image: mariadb:10.11.5-jammy

    networks:
      - paperlessngx

    labels:

      # homepage
      - homepage.group=paperlessngx (.stb.de)
      - homepage.name=paperlessngx-db
      - homepage.description=mariadb:10
      - homepage.showStats=true
      - homepage.icon=mariadb.png

    env_file:
      - ./configuration/db.env

    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db:/var/lib/mysql

    healthcheck:
      test: healthcheck.sh --su=root --connect --innodb_initialized
      start_period: 15s
