networks:

  traefik:
    external: true


services:

  main:

    # https://hub.docker.com/r/paperlessngx/paperless-ngx/tags
    image: paperlessngx/paperless-ngx:1.17.1

    depends_on:

      redis:
        condition: service_healthy
        restart: true

      db:
        condition: service_healthy
        restart: true

    networks:
      - traefik
      - default

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.paperlessngx.rule=Host(`paperlessngx.stb.de`)
      - traefik.http.services.paperlessngx.loadbalancer.server.port=8000

      - traefik.http.routers.paperlessngx.tls.certresolver=stbde
      - traefik.http.routers.paperlessngx.tls.domains[0].main=paperlessngx.stb.de
      - traefik.http.routers.paperlessngx.tls.domains[0].sans=*.paperlessngx.stb.de


      # homepage
      - homepage.group=paperlessngx(.stb.de)
      - homepage.name=main (paperlessngx.stb.de)
      - homepage.weight=-999
      - homepage.description=paperlessngx/paperless-ngx
      - homepage.showStats=true
      - homepage.icon=paperless.png
      - homepage.href=https://paperlessngx.stb.de
      - homepage.ping=https://paperlessngx.stb.de

    restart: unless-stopped

    env_file: ./env/paperlessngx.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/paperless/consume:/usr/src/paperless/consume
      - ./volumes/paperless/data:/usr/src/paperless/data
      - ./volumes/paperless/export:/usr/src/paperless/export
      - ./volumes/paperless/media:/usr/src/paperless/media

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5


  redis:

    image: redis:7.2.0-alpine3.18

    labels:

      # homepage
      - homepage.group=paperlessngx(.stb.de)
      - homepage.name=redis
      - homepage.description=redis:7-alpine
      - homepage.showStats=true
      - homepage.icon=redis.png

    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro

    healthcheck:
      test: redis-cli ping | grep PONG -q
      timeout: 5s
      interval: 15s
      start_period: 10s
      retries: 3


  db:

    # PaperlessNGX: 10.11.5-jammy
    # https://hub.docker.com/_/mariadb/tags
    image: mariadb:10.11.5-jammy

    labels:

      # homepage
      - homepage.group=paperlessngx(.stb.de)
      - homepage.name=db
      - homepage.description=mariadb:10
      - homepage.showStats=true
      - homepage.icon=mariadb.png

    env_file:
      - ./env/db.env

    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db:/var/lib/mysql

    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      timeout: 5s
      interval: 15s
      start_period: 30s
      retries: 3
