networks:

  traefik:
    external: true


services:

  main:

    # https://hub.docker.com/_/nginx/tags?name=alpine
    image: nginx:1.25-alpine3.18

    depends_on:

      fpm:
        condition: service_healthy
        restart: true

      db:
        condition: service_healthy
        restart: true

    networks:
      - traefik
      - default

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.functionaltraining.rule=Host(`functionaltraining.stb.de`)
      - traefik.http.services.functionaltraining.loadbalancer.server.port=80

      - traefik.http.routers.functionaltraining.tls.certresolver=stbde
      - traefik.http.routers.functionaltraining.tls.domains[0].main=functionaltraining.stb.de
      - traefik.http.routers.functionaltraining.tls.domains[0].sans=*.functionaltraining.stb.de


      # homepage
      - homepage.group=functionaltraining(.stb.de)
      - homepage.name=main (functionaltraining.stb.de)
      - homepage.weight=-999
      - homepage.description=nginx:alpine
      - homepage.showStats=true
      - homepage.icon=nginx.png
      - homepage.href=https://functionaltraining.stb.de
      - homepage.ping=https://functionaltraining.stb.de

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./volumes/wordpress:/var/www/html:cached

    restart: unless-stopped

    healthcheck:
      test: curl -s --fail http://localhost
      timeout: 5s
      interval: 15s
      start_period: 30s
      retries: 3


  fpm:

    # https://hub.docker.com/_/wordpress/tags
    image: wordpress:6.3.0-php8.2-fpm-alpine

    depends_on:

      db:
        condition: service_healthy
        restart: true

    labels:

      # homepage
      - homepage.group=functionaltraining(.stb.de)
      - homepage.name=fpm
      - homepage.weight=-100
      - homepage.description=wordpress:fpm-alpine
      - homepage.showStats=true
      - homepage.icon=wordpress.png

    restart: unless-stopped

    env_file:
      - ./env/wordpress.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/wordpress:/var/www/html:cached

    healthcheck:
      test: netstat -tnlp | grep fpm -q
      timeout: 5s
      interval: 15s
      start_period: 10s
      retries: 3


  db:

    # https://hub.docker.com/_/mariadb/tags
    image: mariadb:11.0.3-jammy

    labels:

      # homepage
      - homepage.group=functionaltraining(.stb.de)
      - homepage.name=db
      - homepage.description=mariadb
      - homepage.showStats=true
      - homepage.icon=mariadb.png

    restart: unless-stopped

    env_file:
      - ./env/db.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db:/var/lib/mysql:cached

    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      timeout: 5s
      interval: 15s
      start_period: 30s
      retries: 3
