networks:

  traefik:
    external: true

  functionaltraining:
    enable_ipv6: true

services:

  functionaltraining:

    container_name: functionaltraining
    hostname: functionaltraining

    # https://hub.docker.com/_/nginx/tags?name=alpine
    image: nginx:1.25-alpine3.18

    depends_on:

      functionaltraining-fpm:
        condition: service_healthy
        restart: true

      functionaltraining-db:
        condition: service_healthy
        restart: true

    networks:
      - traefik
      - functionaltraining

    labels:

      # traefik
      - traefik.enable=true
      - traefik.http.routers.functionaltraining.rule=Host(`functionaltraining.stb.de`)
      - traefik.http.services.functionaltraining.loadbalancer.server.port=80

      # homepage
      - homepage.group=functionaltraining (.stb.de)
      - homepage.name=functionaltraining (functionaltraining.stb.de)
      - homepage.weight=-999
      - homepage.description=nginx:alpine
      - homepage.showStats=true
      - homepage.icon=nginx.png
      - homepage.href=https://functionaltraining.stb.de
      - homepage.ping=https://functionaltraining.stb.de

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/nginx:/etc/nginx/conf.d:ro
      - ./volumes/wordpress:/var/www/html:cached

    restart: unless-stopped

    healthcheck:
      test: curl -s --fail http://localhost

  functionaltraining-fpm:

    container_name: functionaltraining-fpm
    hostname: functionaltraining-fpm

    # https://hub.docker.com/_/wordpress/tags
    image: wordpress:6.3.0-php8.2-fpm-alpine

    networks:
      - functionaltraining

    depends_on:

      functionaltraining-db:
        condition: service_healthy
        restart: true

    labels:

      # homepage
      - homepage.group=functionaltraining (.stb.de)
      - homepage.name=functionaltraining-fpm
      - homepage.weight=-100
      - homepage.description=wordpress:fpm-alpine
      - homepage.showStats=true
      - homepage.icon=wordpress.png

    restart: unless-stopped

    env_file:
      - ./configuration/wordpress.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/wordpress:/var/www/html:cached

    healthcheck:
      test: netstat -tnlp | grep fpm -q

  functionaltraining-db:

    container_name: functionaltraining-db
    hostname: functionaltraining-db

    # https://hub.docker.com/_/mariadb/tags
    image: mariadb:11.0.3-jammy

    networks:
      - functionaltraining

    labels:

      # homepage
      - homepage.group=functionaltraining (.stb.de)
      - homepage.name=functionaltraining-db
      - homepage.description=mariadb
      - homepage.showStats=true
      - homepage.icon=mariadb.png

    restart: unless-stopped

    env_file:
      - ./configuration/db.env

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/db:/var/lib/mysql:cached

    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 15s
